import './globals.css'
import { Inter } from 'next/font/google'
import Header from './Header/page';
import CheackedContextProvider from "../Context/Cheacked_Context";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CheackedContextProvider >
      <body className={`${inter.className} body` }>
        <div className="relative" id="top-scroll">
        <Header />
        {children}
        </div>
        </body>
        </CheackedContextProvider>
    </html>
  )
}
